
export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS"
export const EDITAR_PROJETOS = "EDITAR_PROJETOS"
export const DELETAR_PROJETOS = "DELETAR_PROJETOS"
export const VERIFICAR_PROJETO = "VERIFICAR_PROJETOS"
export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CADASTRAR_TAREFAS = "CADASTRAR_TAREFAS"
export const EDITAR_TAREFA= "EDITAR_TAREFA"